services:

  desktop:
    image: octodrive:latest
    networks:
      - octo-net
    environment:
      - DISPLAY=${DISPLAY}
      - GSETTINGS_BACKEND=memory
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/root/app
    command: ["./build/bin/octodrive"]

  server:
    image: alpine:latest
    networks:
      - octo-net
    working_dir: /root/app
    volumes:
      - ./server/bin:/root/app/bin
    command: ["./bin/server"]
    

networks:
  octo-net:
    driver: bridge